# Generated by Django 4.2.6 on 2023-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('movies', 'Movie'), ('books', 'Book')], max_length=10),
        ),
    ]
